spring.datasource.url=jdbc:mysql://localhost:3306/attendence_db
spring.datasource.username=root
spring.datasource.password=Archita@27

jwt.secret=bXktc21hcnQtYXR0ZW5kYW5jZS1qd3Qtc2VjcmV0LWtleS0yMDI2LXZlcnktc2VjdXJl
jwt.expiration=86400000

spring.jpa.show-sql=true